---
sudo: required

language: generic

env:
  matrix:
    - distribution: ubuntu
      version: 14.04
    - distribution: ubuntu
      version: 16.04
    - distribution: centos
      version: 6
    - distribution: centos
      version: 7

services:
  - docker

script:
  - ./tests/test_inside_docker.sh ${distribution} ${version}
